import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "@/styles/_index.scss";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/lib/auth";
import getFonts from "@/hooks/useFont";

export const metadata: Metadata = {
  title: "Sporting Karaté Club",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { quicksand } = getFonts();
  const session = await auth();
  return (
    <html lang="fr">
      <body className={quicksand}>
        <SessionProvider session={session}>{children}</SessionProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
